name: ${group}.fastmapper
version: ${version}
main: org.lime.fastmapper.FastMapperPlugin
libraries:
  - com.google.protobuf:protobuf-java:${versionProtobuf}
  - io.grpc:grpc-protobuf:${versionGrpc}
  - io.grpc:grpc-stub:${versionGrpc}
  - io.grpc:grpc-auth:${versionGrpc}
  - io.grpc:grpc-netty:${versionGrpc}
api-version: '1.21'
authors: [Lime]
softdepend:
  - ${group}.core